test:new(function (test, sim)
    local client = sim:connect({ "test" })
    sim:loadAndStart('examples', 'simple-test')
    sim:doTicks()
end, 'RUN', 'HELIX'):run()

test:new(function (test, sim)
    local client = sim:connect({ "test" })
    local client2 = sim:connect({ "test2" })
    sim:loadAndStart('examples', 'simple-test')
    sim:doTicks()
end, '2Clients', 'HELIX'):run()
